name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    env:
      TF_VAR_ZEDCLOUD_TOKEN: ${{ vars.TF_VAR_ZEDCLOUD_TOKEN }}
      TF_VAR_zedcloud_url : ${{ vars.TF_VAR_zedcloud_url }}
      TF_LOG : ${{ vars.TF_LOG }}
      TF_LOG_PATH : ${{ vars.TF_LOG_PATH }}
      TF_CLI_CONFIG_FILE: ${{ vars.TF_CLI_CONFIG_FILE }}

    steps:
    - uses: actions/checkout@v4

    - name: make build
      run:  make build

    - name: make test
      run: make test

